apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql
spec:
    replicas: 2
    selector:
        matchLabels:
        app: db-mysql
    template:
        metadata:
        labels:
          app: db-mysql
        spec:
        containers:
        - name: db-mysql
          image: leonardojr96/db-mysql
          ports:
          - containerPort: 8000